version: "3"

services:

  back:
    image: node:16-alpine
    container_name: estudos_back
    working_dir: /app
    restart: always

    stdin_open: true
    tty: true

    command: sh

    ports:
     - 3001:3001
    depends_on:
      - db
    volumes:
      - ./:/app

    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3307

  db:
    image: mysql:8.0.23
    container_name: estudos_db
    restart: always

    ports:
      # Expõe a porta padrão do banco de dados
      - 3307:3306
      
    environment:
      MYSQL_ROOT_PASSWORD: password 